add_newline = false
command_timeout = 1000

format = """
[arch](green bold) in \
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$character"""

[character]
success_symbol = "[λ](bold red)"
error_symbol = "[λ](bold red)"

[directory]
read_only = " "
format = "[$path]($style) "
style = "bold red"

[git_branch]
format = "[󰘬 $branch]($style)"
style = "bold bright-black"

[git_status]
format = " [$conflicted$untracked$modified$staged$renamed$deleted$ahead_behind$stashed ]($style)"
style = "cyan"
conflicted = ""
untracked = ""
modified = ""
staged = ""
renamed = ""
deleted = ""
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bold bright-black"

[cmd_duration]
format = "[󱦟 $duration]($style)"
style = "yellow"
